name: Build and Deploy for ATM Backend to AWS EC2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_NAME: ATM_Backend
  BUCKET_NAME: atm-backend-github-action-s3-bucket
  CODE_DEPLOY_APP_NAME: atm-backend
  DEPLOYMENT_GROUP_NAME: atm-backend-group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Check build output
        run: ls -la build/libs

      - name: Upload JAR to S3
        run: |
          JAR_NAME=$(ls build/libs/ | grep 'SNAPSHOT.jar' | tail -n 1)
          if [ -z "$JAR_NAME" ]; then
            echo "JAR 파일을 찾을 수 없습니다."
            exit 1
          fi
          echo "Uploading $JAR_NAME to S3"
          aws s3 cp build/libs/$JAR_NAME s3://$BUCKET_NAME/$PROJECT_NAME/$JAR_NAME --region ap-northeast-2

      - name: Code Deploy To EC2 instance
        run: |
          aws deploy create-deployment \
            --application-name $CODE_DEPLOY_APP_NAME \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name $DEPLOYMENT_GROUP_NAME \
            --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip


