name: Build and Deploy for ATM Backend to AWS EC2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

env:
  PROJECT_NAME: ATM_Backend
  BUCKET_NAME: atm-backend-github-action-s3-bucket
  CODE_DEPLOY_APP_NAME: atm-backend
  DEPLOYMENT_GROUP_NAME: atm-backend-group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build/libs/*.jar s3://$BUCKET_NAME/$PROJECT_NAME/

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment \
          --application-name $CODE_DEPLOY_APP_NAME \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name $DEPLOYMENT_GROUP_NAME \
          --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
